### ISSUE TITLE
Bare Metal Hosts Masters have no Nodes attached

### ISSUE THREAD

**Issue by cdvultur** [openshift-kni/baremetal-deploy#102]
While deploying new cluster, the BMH Masters that are 'Externally Provisioned' do not have any Nodes attached to it. 

Basically the problems is discussed in  [here](https://github.com/metal3-io/baremetal-operator/issues/242), and dev-scripts used [this](https://github.com/openshift-metal3/dev-scripts/blob/master/12_csr_hack.sh#L9-L14) workaround.

The environment is using libvirt and linchpin. 

This is how currently it looks like: 
![image](https://user-images.githubusercontent.com/54892201/71196117-a1e49000-228f-11ea-90ed-5308811a90a3.png)

**Comment by rlopez133** [comment]
@cdvultur is this still an issue? The workaround file doesn't exist anymore.

**Comment by cdvultur** [comment]
Yes, the issue still persists. As for the fix git history seems the only option.

**Comment by rlopez133** [comment]
Since issues 242 was closed, closing as well.

**Comment by cdvultur** [comment]
@rlopez133 
On a system with 4.4.4 I can still see the exact same screen from above. 
Same for 4.5 from nightly, same behavior.

Is this a new fix, from latest 24 hours ? My cluster are a few days old.

**Comment by rlopez133** [comment]
Hi @cdvultur , I don't have a fix. I'm just going by what I saw in the original PR you mentioned https://github.com/metal3-io/baremetal-operator/issues/242 which has been closed. Since our team wouldn't be the ones to fix this, I closed this as well. Maybe the best course of action would be to comment directly in PR 242 if they plan on fixing this?

**Comment by cdvultur** [comment]
Thanks for the response @rlopez133 
I asked on the specified PR what is the desired action on this topic.
