### ISSUE TITLE
Unneeded packages

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/baremetal-deploy#105]
https://github.com/openshift-kni/baremetal-deploy/blob/fe314d528bc107f40f0f60de6612717e3fbf5c08/baremetal-prep/baremetal-prep.sh#L151

There are a few packages not needed that were used back in the day where a iso was needed. To improve the installation time, the packages installed need to be reduced.

Also, if they are installed as dependency of other packages, they should not be explicitly added.

**Comment by rlopez133** [comment]
@e-minguez can we close this out in favor of the Ansible playbook going forward?
