### ISSUE TITLE
Yum install once

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/baremetal-deploy#106]
Currently there is a function that install required packages (https://github.com/openshift-kni/baremetal-deploy/blob/master/baremetal-prep/baremetal-prep.sh#L159) and other yum install here (https://github.com/openshift-kni/baremetal-deploy/blob/master/baremetal-prep/baremetal-prep.sh#L56)
It would be nice to add the required packages to the list of the dependencies instead installing it in another yum call.

**Comment by sreichar** [comment]
My read of this is the second install is happening only when a self host registry is being configured for disconnected.  The packages would not be needed otherwise.  

Do you think they should be installed when not needed?

**Comment by e-minguez** [comment]
> My read of this is the second install is happening only when a self host registry is being configured for disconnected. The packages would not be needed otherwise.
> 
> Do you think they should be installed when not needed?

```
install_depends(){
  PACKAGES="ansible git usbredir golang libXv virt-install libvirt libvirt-devel libselinux-utils qemu-kvm mkisofs python3-devel jq ipmitool"
  EXTRA_PACKAGES="podman httpd httpd-tools"
  [ "$ENABLEDISCONNECT" -eq "1" ] && PACKAGES+=" ${EXTRA_PACKAGES}"
  echo "Installing required dependencies..."
  echo ${PACKAGES}
}
```

Also, it would be nice to use a http container instead installing httpd (containers everywhere!)

**Comment by e-minguez** [comment]
Just in case, an example: https://github.com/e-minguez/ocp4-upi-bm-pxeless-staticips/blob/master/docs/3-web-server.md

**Comment by rlopez133** [comment]
@e-minguez @sreichar - Once we get disconnected installs and cacheing as part of the Ansible playbook, can we retire baremetal-prep.sh?

**Comment by rlopez133** [comment]
Closing as we are not going to make any enhancements to baremetal-prep.sh
