### ISSUE TITLE
install-steps.md Drops connection when configuring bridges via ssh.

### ISSUE THREAD

**Issue by jobbler** [openshift-kni/baremetal-deploy#108]
When configuring the bridges on the provision node via ssh, the connection will drop when removing the interface the connection is on. This can prevent all the commands from running if copy/pasted and prevents the ability to finish the configuration.

This can be fixed by wrapping the commands using nohup.
example: nohup bash -c 'nmcli commands'
Using nohup, once the configuration is done, the connection should resume.

Also, the steps will create a temporary connection called "Wired connection ..." when the interface is removed if the interface is active when it is removed.
Need to bring the interfaces down before removing them.

**Comment by rlopez133** [comment]
Adding your nohup fix to the doc
