### ISSUE TITLE
install-steps.md provision_ip in metal3 yaml

### ISSUE THREAD

**Issue by jobbler** [openshift-kni/baremetal-deploy#113]
A note exists under step 4 when creating the metal3-config.yaml.sample file.
The note states that the provision_ip should be modified to an available ip.

First, this should be provisioning_ip in the note. Also, it should be noted that in the config file, the deploy_kernel_url, deploy_ramdisk_url, ironic_endpoint, and ironic_inspector_endpoint should have the same ip as the provisioning_ip.

**Comment by rlopez133** [comment]
I'll make those fixes shortly.
