### ISSUE TITLE
install-steps.md Number of routers deployed

### ISSUE THREAD

**Issue by jobbler** [openshift-kni/baremetal-deploy#114]
The "Deploying Routers on Worker Nodes" mentions setting the replicas for the routers to be the same as the number of worker nodes deployed.

If no worker nodes are deployed during installation, what value should this be set to?
For instance, if i will have one worker node added after installation because it is the node i am provisioning from.

Can this be adjusted later? Do i set it to 0 during installation and then how do i increment it when i reconfigure the provisioning system to be a worker.

**Comment by rlopez133** [comment]
Hi @jobbler - If you are doing a 3 master, 0 worker you don't need to change the value. What will happen is 2 of your masters will contain 2 routers.
