### ISSUE TITLE
[RFE] of ansible-ipi-install - Handle addressing other than ipmi

### ISSUE THREAD

**Issue by rlopez133** [openshift-kni/baremetal-deploy#133]
Have the ability to have address in install-config.yml use something other than IPMI

**Comment by iranzo** [comment]
Should this be closed as we have https://github.com/openshift-kni/baremetal-deploy/issues/134 for covering redfish? or has different scope?

**Comment by rlopez133** [comment]
@iranzo yeah we can close this.
