### ISSUE TITLE
Documentation: Missing prereq for ansible-ipi-install

### ISSUE THREAD

**Issue by cwilkers** [openshift-kni/baremetal-deploy#143]
Attempting to use roles by include_role and tasks_from fails in `10_validation.yml` with

`TASK [node-prep : Verify DNS records for API VIP, Wildcard (Ingress) VIP] **************************
Thursday 06 February 2020  00:32:37 +0000 (0:00:00.130)       0:00:03.060 ***** 
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'dig'. Error was a <class 'ansible.errors.AnsibleError'>, original message: The dig lookup requires the python 'dnspython' library and it is not installed"}
`

**Comment by rlopez133** [comment]
https://github.com/openshift-kni/baremetal-deploy/tree/master/ansible-ipi-install#dig-lookup-requires-the-python-dnspython-library-and-it-is-not-installed

This is because the playbook uses dig lookup which requires your control machine to have the python3-dns package.
