### ISSUE TITLE
SELinux disabled?

### ISSUE THREAD

**Issue by MarSik** [openshift-kni/baremetal-deploy#16]
I just noticed selinux is disabled in the baremetal-prep.sh script here https://github.com/openshift-kni/baremetal-deploy/blob/master/baremetal-prep/baremetal-prep.sh#L222

Is this really needed? Maybe we need a comment explaining why that is so.

**Comment by schmaustech** [comment]
Both cstark and I have tested without it disabled and agree we can remove it.  This originally came out of dev-scripts.

**Comment by schmaustech** [comment]
PR #21 Fixes

**Comment by sreichar** [comment]
Since #21 was merged, this can now be closed.
