### ISSUE TITLE
baremetal-deploy/install-steps.md hostnames are inconsistent

### ISSUE THREAD

**Issue by ipilcher** [openshift-kni/baremetal-deploy#181]
It would really nice to have the hostname/DNS record requirements clearly stated.  install-steps.md uses `master-{0,1,2}` and `worker-{0,1}` at one point, but then it uses `openshift-master-{0,1,2}` and `openshift-worker-{0,1}` later on.  At a minimum it should be consistent.

It's also unclear what, if any, requirements the installer imposes on these hostnames.

**Comment by rlopez133** [comment]
Sure can fix that. I do believe there is a requirement of host name having the naming master- and worker-0 , so yeah both those can be added.

**Comment by rlopez133** [comment]
@ipilcher can you take a look at the PR linked above and let me know if it is to your liking? Thanks.
