### ISSUE TITLE
[RFE] Ability to inject ones own install-config.yaml

### ISSUE THREAD

**Issue by rlopez133** [openshift-kni/baremetal-deploy#193]
There will be times where we can't automate every scenario, every tweak required on an environment. Due to this, it would be great to give customer the ability to provide their own install-config.yaml file versus us always generating one.

**Comment by iranzo** [comment]
I would say that we allow to define a custom path to a file, and based on it we either copy that file to final destination or we do use the template as defined in `ansible-ipi-install/roles/installer/tasks/25_create-install-config.yml`

Alternatively we might offer to use their file as template, but that will be over complicating this vs just modifying the one in the installation folder with whatever is needed

What is the use case of this?

**Comment by rlopez133** [comment]
@iranzo use case for this would be there is no way we can programatically catch ever install-config parameter to be included in the playbook. The goal would be if a user has a install config that we just won't properly generate because we don't have the logic in the code they can provide one instead and still take advantage of the playbook. I think defining a custom path would be the goal and something to the effect on when: <some parameter> is not defined for existing install-config yaml tasks and when: <some parameter> is defined for when you want to use the one you're providing. obviously im sure there are more (better) routes but this is what crossed my mind as I typed this :)
