### ISSUE TITLE
Run the rhcos_image_cache container as the kni user

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/baremetal-deploy#199]
Currently the ansible playbooks run the podman rhcos_image_cache container as root user (become: yes). As the port exposed is 8080 (no need to bind to <1024, hence, no need for the container to be executed as root), I think it would be better to run the container as a regular user instead.

**Comment by abays** [comment]
Good point.  We initially exposed it at 80, but using kni user makes sense with the change to 8080.
