### ISSUE TITLE
Unable to untar the oc binary form the OpenShift Installer (GA Release) 

### ISSUE THREAD

**Issue by vanchikovan** [openshift-kni/baremetal-deploy#200]
### Unable to untar the oc binary form the OpenShift Installer (GA Release) 

export VERSION=latest-4.3
export RELEASE_IMAGE=$(curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$VERSION/release.txt | grep 'Pull From: quay.io' | awk -F ' ' '{print $3}' | xargs)

When the oc binary untar, it is failed due to the VERSION, If $VERSION is declared as latest-4.3 as above . 

# Get the oc binary
curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$VERSION/openshift-client-linux-$VERSION.tar.gz | tar zxvf - oc

**Comment by vanchikovan** [comment]
### While Retrieving the OpenShift Installer (GA Release) , the latest-4.3 version is pointing to version 4.3.1 in the installer link.

### The version latest-4.3 on this file(openshift-client-linux-$VERSION.tar.gz) is pointing to 4.3.1 only. 

So the $VERSION should be decaled as 4.3.1 to get the oc binary.
**export VERSION=4.3.1**

**Comment by rlopez133** [comment]
Hi @vanchikovan , I've fixed the issue and the new changes should be merged shortly. Thanks for reporting!
