### ISSUE TITLE
RHCOS cache container should bind on all addresses to support IPv6

### ISSUE THREAD

**Issue by yprokule** [openshift-kni/baremetal-deploy#224]
To support ipv6 `rhcos_image_cache` should be able to  bind on IPv6 addresses.

Seems podman's  `--net host` option allows achieve this.

**Comment by abays** [comment]
This also would require the `httpd` conf inside the container to bind a socket on the ipv6 stack, which it does not do by default.  So we would need to modify the conf appropriately.

**Comment by rlopez133** [comment]
@abays seems like we an achieve this with the `--net host` only sucky part is its insecure. From the podman-run man page
```
       · host: use the Podman host network stack. Note: the host mode gives the container full access to
         local system services such as D-bus and is therefore considered insecure.
```

However, they have yet to implement `--ip6` so I'd say for now we should just run it with `--net host` as the playbook is not intended for production anyway. At least those are my 2 cents. @e-minguez thoughts here?

**Comment by abays** [comment]
Even with the `--net host`, however, we still need to change the Apache config within the container to listen on ipv6.  The default conf file has it listen on `0.0.0.0:8080`.  My understanding is that we would need to modify the conf and add `[::]:8080`.

**Comment by sreichar** [comment]
@schmaustech 

Can you share how you handled this?

**Comment by rlopez133** [comment]
> Even with the `--net host`, however, we still need to change the Apache config within the container to listen on ipv6. The default conf file has it listen on `0.0.0.0:8080`. My understanding is that we would need to modify the conf and add `[::]:8080`.

Confirmed that adding `--net host` allows the container to listen to the webserver.
