### ISSUE TITLE
Multiple documentation issues

### ISSUE THREAD

**Issue by ipilcher** [openshift-kni/baremetal-deploy#232]
We're showing the commands to download the RHCOS images as:
```
curl -L ${RHCOS_PATH}${RHCOS_QEMU_URI} -o /home/kni/rhcos_image_cache
curl -L ${RHCOS_PATH}${RHCOS_OPENSTACK_URI} -o /home/kni/rhcos_image_cache
```
But this gives an error:
```
Warning: Failed to create the file /home/kni/rhcos_image_cache: Is a directory
```
Using curl with `-o` in this way will require the complete output file name.

**Comment by ipilcher** [comment]
This could be it's own issue, but I'm going to be lazy.  We're also missing `firewall-cmd --reload` in this section.

**Comment by ipilcher** [comment]
Changing issue title.

We also have this in the `metal3-config.yaml.sample`:
```
rhcos_image_url: ${RHCOS_PATH}${RHCOS_URI}
```
But `RHCOS_URI` isn't set.  I think it should be `RHCOS_OPENSTACK_URI`?

**Comment by ipilcher** [comment]
The `install-config.yaml` example seems to be missing `provisioningNetworkInterface`.
```
FATAL failed to fetch Master Machines: failed to load asset "Install Config": invalid "install-config.yaml" file: platform.baremetal.provisioningNetworkInterface: Invalid value: "": no provisioning network interface is configured, please set this value to be the interface on the provisioning network on your cluster's baremetal hosts 
```

**Comment by rlopez133** [comment]
> Changing issue title.
> 
> We also have this in the `metal3-config.yaml.sample`:
> 
> ```
> rhcos_image_url: ${RHCOS_PATH}${RHCOS_URI}
> ```
> 
> But `RHCOS_URI` isn't set. I think it should be `RHCOS_OPENSTACK_URI`?
> 
> EDIT: Also, should I be using the same URL as clusterOSImage (from `install-config.yaml`) if I've set up an image cache?

This part should be taken care of by step 6 which does the exporting of those variables (regarding RHCOS_URI)

Regarding the bootstrapOSImage and clusterOSImage, they are different values: bootstrapOSImage uses the RHCOS_QEMU_URI and clusterOSImage uses the RHCOS_OPENSTACK_URI

**Comment by rlopez133** [comment]
> The `install-config.yaml` example seems to be missing `provisioningNetworkInterface`.
> 
> ```
> FATAL failed to fetch Master Machines: failed to load asset "Install Config": invalid "install-config.yaml" file: platform.baremetal.provisioningNetworkInterface: Invalid value: "": no provisioning network interface is configured, please set this value to be the interface on the provisioning network on your cluster's baremetal hosts 
> ```

This is true if you are deploying OCP 4.4. The document references version 4.3 . Still trying to work in everything for the newer stuff.

**Comment by rlopez133** [comment]
@ipilcher - if anything else let me know -- merged.
