### ISSUE TITLE
OpenShift Container Platform 4.3 Documentation

### ISSUE THREAD

**Issue by prabinovRedhat** [openshift-kni/baremetal-deploy#277]
My name is Polina, I am a student from the QE team of Arik and Amit.
Our team checked this [document 4.3](https://docs.openshift.com/container-platform-ocp/4.3/welcome/index.html) and we found some inaccuracies/errors.
In the **Installing->Deploying IPI Bare Metal->Setting up the environment for an OpenShift installation**
In the part of **"Configuring the metal3-config file (OpenShift Container Platform 4.3 only)"** there is an error in order of parameters **rhcos_image_url** there written:
rhcos_image_url: ${RHCOS_PATH}${RHCOS_URI}, but true so: 
**rhcos_image_url: ${RHCOS_URI}${RHCOS_PATH}‌**. 
As well as variables RHCOS_URI and RHCOS_PATH that exports right after creation of metal3-config.yaml.sample they are not true, **here i write how it should be:**
**export RHCOS_URI=$(curl -s -S https://raw.githubusercontent.com/openshift/installer/$COMMIT_ID/data/data/rhcos.json | jq .baseURI | sed 's/"//g')**
**export RHCOS_PATH=$(curl -s -S https://raw.githubusercontent.com/openshift/installer/$COMMIT_ID/data/data/rhcos.json | jq .images.openstack.path | sed 's/"//g')**

**Comment by iranzo** [comment]
Hi Polina,
I cannot access the url you link in 'document 4.3', Official fixes to documentation can go via bugzilla.redhat.com  issues targetting the documentation like this bz: https://bugzilla.redhat.com/show_bug.cgi?id=1805125

**Comment by rlopez133** [comment]
Thank you @prabinovRedhat , I'll get this fixed in our install-steps.md

**Comment by prabinovRedhat** [comment]
@iranzo, I opened the same in Bugzila.
And this is a link (with user and password)
https://docs.openshift.com/container-platform-ocp/4.3

Username: openshift
Password: early-access

**Comment by prabinovRedhat** [comment]
@rlopez133 , Thank you!

**Comment by iranzo** [comment]
Affected file for documentation is: https://docs.openshift.com/container-platform-ocp/4.3/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html

**Comment by rlopez133** [comment]
@prabinovRedhat regarding the RHCOS_URI and RHCOS_PATH, the new value you provided for them looks exactly like what is already in the document.

**Comment by prabinovRedhat** [comment]
@rlopez133 , Now it's:
export COMMIT_ID=$(./openshift-baremetal-install version | grep '^built from commit' | awk '{print $4}')
**export RHCOS_URI**=$(curl -s -S https://raw.githubusercontent.com/openshift/installer/$COMMIT_ID/data/data/rhcos.json | jq .images.openstack.path | sed 's/"//g')
**export RHCOS_PATH**=$(curl -s -S https://raw.githubusercontent.com/openshift/installer/$COMMIT_ID/data/data/rhcos.json | jq .baseURI | sed 's/"//g')
envsubst < metal3-config.yaml.sample > metal3-config.yaml
