### ISSUE TITLE
Unscapped variables in task titles

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/baremetal-deploy#291]
There are some task titles that have variables like:

```
TASK [installer : Ensure the manifests dir is owned by {{ ansible_user }}] *****
```

**Comment by rlopez133** [comment]
What are your thoughts on how to handle it? My understanding is ansible shows this because it can't definitively define who that user is thus it leaves the variable instead of the value.

**Comment by rlopez133** [comment]
I'm going to close this because the {{ ansible_user }} shows up because ansible can't determine this dynamically. The best I can do is either change it to the word user, which doesn't say much or I can say ansible_user without the {{ }} but effectively i see that as the same thing.
