### ISSUE TITLE
Baremetal network cannot be a vlan

### ISSUE THREAD

**Issue by yrobla** [openshift-kni/baremetal-deploy#292]
In my setup in my local lab, i need to use a vlan for baremetal network, not just a plain nic. I am passing this to the playbook as pub_nic=eno2.1
But playbook is still creating an ethernet type, not a vlan:
eno2.1        28e9c4b4-911a-416e-9028-55f0906b1968  ethernet  --

Can vlans be supported for this playboook, or do we always need to provide nics? Thanks!

**Comment by rlopez133** [comment]
Hi @yrobla we can definitely open a RFE for it, however it doesn't support it at this time. The best way to get around this would be to setup your network bridges manually as you need. When you run the playbook add to your command `--skip-tags=network` , where this will skip the code that does anything related to created bridges.
