### ISSUE TITLE
[RFE] Allow different interfaces for provisioner and masters

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/baremetal-deploy#296]
Currently, prov_nic is being used to create the bridges in the provisioner host as well as the `provisioningNetworkInterface` parameter in the install-config.yaml
If the provisioner host and master hosts have different interfaces, this won't work.
The idea is to have a `prov_nic` as currently but also an optional `provisioningNetworkInterface` that will get by default the same value as `prov_nic` or a custom one if defined.

https://github.com/openshift-kni/baremetal-deploy/blob/master/ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml

https://github.com/openshift-kni/baremetal-deploy/blob/master/ansible-ipi-install/roles/installer/templates/install-config.j2

**Comment by rlopez133** [comment]
The consensus on this issue (has it has been brought up before) is that playbook would follow the best practice guidelines from our install steps which is that provisioning nic would match the provisioning network interface.

**Comment by e-minguez** [comment]
> The consensus on this issue (has it has been brought up before) is that playbook would follow the best practice guidelines from our install steps which is that provisioning nic would match the provisioning network interface.

While I agree on the best practice, it also means that it blocks the ability to have different hardware from the provisioner and the masters. Imagine for instance, in your provisioner host (like a small one) you can have embedded nics `eno1` but your masters have `enp0s...`.

The real requirement is the masters have the same nic (for the `provisioningNetworkInterface `parameter), but the playbooks artificially 'reuse' that parameter to build the bridges.

It would be just a couple of lines. If you find this interesting I can send a PR.
