### ISSUE TITLE
Playbook errors with a incorrect error when ansible is <2.9

### ISSUE THREAD

**Issue by colonwq** [openshift-kni/baremetal-deploy#333]
When using ansible 2.8, the playbook exits with a language error when it should exit with a wrong version error. 

*** With ansible 2.8

TASK [node-prep : include_tasks] **********************************************************************************************************************************************************************************
Tuesday 28 April 2020  15:14:58 -0400 (0:00:01.483)       0:00:01.536 *********
fatal: [provision.osp.example.com]: FAILED! => {"reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module path.\n\nThe error appears to be in '/home/kni/baremetal-deploy/ansible-ipi-install/roles/node-prep/tasks/10_validation.yml': line 13, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Ensure Python libraries are installed\n  ^ here\n"}

PLAY RECAP ********************************************************************************************************************************************************************************************************
provision.osp.example.com  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0              

*** With ansible 2.9

TASK [node-prep : include_tasks] **********************************************************************************************************************************************************************************
Tuesday 28 April 2020  15:22:11 -0400 (0:00:02.595)       0:00:02.631 *********
included: /home/kni/baremetal-deploy/ansible-ipi-install/roles/node-prep/tasks/10_validation.yml for provision.osp.example.com                                                                                    

TASK [node-prep : Check ansible version] **************************************************************************************************************************************************************************
Tuesday 28 April 2020  15:22:11 -0400 (0:00:00.194)       0:00:02.826 *********
ok: [provision.osp.example.com -> localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [node-prep : Ensure Python libraries are installed] **********************************************************************************************************************************************************
Tuesday 28 April 2020  15:22:11 -0400 (0:00:00.056)       0:00:02.882 *********
ok: [provision.osp.example.com -> localhost]

**Comment by iranzo** [comment]
Hi,
In the requirements for Ansible at https://github.com/openshift-kni/baremetal-deploy/tree/master/ansible-ipi-install it's stated to use ansible 2.9 or greater.

However, I'll add a check for failing earlier when ansible version is not satisfied

**Comment by iranzo** [comment]
Theoretically it should be failing here: https://github.com/openshift-kni/baremetal-deploy/blob/master/ansible-ipi-install/roles/node-prep/tasks/10_validation.yml#L5

**Comment by colonwq** [comment]
I spoke with Roger L about this failure yesterday. He had a ideas about the cause of the error.

**Comment by rlopez133** [comment]
This is likely do to how the asset module has changed from what it is in 2.9 versus previous versions

**Comment by iranzo** [comment]
@colonwq can you check PR 382 to see if it works as expected?
