### ISSUE TITLE
Containers (registry, rhcos_image_cache) won't start up automatically on reboot

### ISSUE THREAD

**Issue by rlopez133** [openshift-kni/baremetal-deploy#334]
Currently if the nodes hosting the containers is rebooted, the containers do not automatically restart. Goal here is to have containers restart on a reboot of the provisioner/registry node. To fix this we need to create a systemd service.

Notes from John Herr how he did this:

As the kni user do all the following:
sudo loginctl enable-linger kni
mkdir -p ~/.config/systemd/user
podman generate systemd --name ocpdiscon-registry > .config/systemd/user/registry.service
See what targets are available, there should be a default.target.
Verify that default.target exists.
systemctl --user -t target 
Change the WantedBy= line in the registry.service file to be WantedBy=default.target
systemctl --user enable registry.service

You can shorten that also by doing the following:
podman generate systemd --name mirrored-registry | sed 's/\(^WantedBy=\).*$/\1default.target/'

NOTE: Add user=kni to the service so that you don't require the systemctl --user piece

**Comment by rlopez133** [comment]
In order to Ansiblize, likely will need to template the service file and then copy it to the appropriate dir and provide appropriate permissions

**Comment by sreichar** [comment]
Should these be kubernetes static pods instead of using systemd?

**Comment by rlopez133** [comment]
@sreichar - can't be k8s static pods because there is no k8s running -- pre-deployment

**Comment by e-minguez** [comment]
Maybe we can take a look at something like https://github.com/kelseyhightower/standalone-kubelet-tutorial/blob/master/README.md
Like a single systemd unit that spins up a standalone kubelet, then all the other containers are just static pods.

**Comment by e-minguez** [comment]
Also https://github.com/containers/libpod/blob/master/docs/source/markdown/podman-generate-systemd.1.md
```
podman-generate-systemd - Generate systemd unit file(s) for a container or pod
```

**Comment by rlopez133** [comment]
@e-minguez yeah I'm planning on going that route (generate systemd) as it requires less changes in the playbook overall. Hoping to have something PR'd today/tomm
