### ISSUE TITLE
Backup of ignition configs is outside of block that generates configs

### ISSUE THREAD

**Issue by dustinblack** [openshift-kni/baremetal-deploy#345]
PR #337 added a backup task for ignition config files, but that task is outside of the conditional block that would generate the files. If that block is not triggered, then no ignition config files will be created, and the backup task will fail.

**Comment by smalleni** [comment]
I think master.ign and worker.ign should exist even if the block was not entered as they are being copied inside the block https://github.com/openshift-kni/baremetal-deploy/blob/master/ansible-ipi-install/roles/installer/tasks/55_customize_filesystem.yml#L21

**Comment by smalleni** [comment]
Never mind, the ignition configs are created inside the block.
