### ISSUE TITLE
provisioningDHCPRange is missing from docs

### ISSUE THREAD

**Issue by stbenjam** [openshift-kni/baremetal-deploy#405]
I don't see it mentioned on https://openshift-kni.github.io/baremetal-deploy/4.4/Deployment.html#configuring-the-install-config-file_ipi-install-prerequisites

More info here:
https://github.com/openshift/installer/blob/master/docs/user/metal/customization_ipi.md

**Comment by iranzo** [comment]
Hi @stbenjam 
We've some parameters listed as additional in the https://openshift-kni.github.io/baremetal-deploy/4.4/Deployment.html#additional-install-config-parameters_ipi-install-prerequisites 

Would be listing the DHCPRange parameter in the sample install-config be enough as I don't see it listed as required in the customization_ipi but just an optional one that can be used (similar to the provisioningDHCPExternal we were discussing the other day).

Thanks for clarifying

**Comment by stbenjam** [comment]
@iranzo Yea that makes sense, it's optional.

**Comment by iranzo** [comment]
@stbenjam You can preview the changes at https://deploy-preview-418--baremetal-deploy.netlify.app/4.4/deployment#configuring-the-install-config-file_ipi-install-prerequisites

I've also added the DHCPExternal and marked them as (OPTIONAL)

@rlopez133 can you provide feedback on the PR too?

**Comment by stbenjam** [comment]
Hm, looking at it now, I think it might be nice to have a dedicated section to all the optional parameters with descriptions. Many of the other parameters listed actually have defaults and don't need to be specified. 

`provisioningNetworkCIDR` is also optional, we have a default. And there's a whole bunch of settings related to that like the DHCP range, which IP's are used for boostrap and provisioning, etc that are also optional that probably should be described.

**Comment by rlopez133** [comment]
I thought the same thing when you PR'ed it. We'll get it fixed next week. Theres some stuff with additional install configs where i wanna add required, optional

**Comment by iranzo** [comment]
> Hm, looking at it now, I think it might be nice to have a dedicated section to all the optional parameters with descriptions. Many of the other parameters listed actually have defaults and don't need to be specified.
> 
> `provisioningNetworkCIDR` is also optional, we have a default. And there's a whole bunch of settings related to that like the DHCP range, which IP's are used for boostrap and provisioning, etc that are also optional that probably should be described.

I had it updated in the PR as optional, I'm moving the provisioningNetwork CIDR there too

**Comment by rlopez133** [comment]
Fixed in docs.
