### ISSUE TITLE
No documentation re: provisioning network ipv4 configuration

### ISSUE THREAD

**Issue by larsks** [openshift-kni/baremetal-deploy#416]
While the documentation contains some bits of information concerning the ipv6 configuration of the provisioning network, it is completely silent on the topic of ipv4 configuration.

- Should the operator assign an ip address to the `provisioning` interface, or will the installer do that?
- If the operator assigns the address, does it have to be the `.1` address?
- What address will be assigned to the bootstrap vm? Can this be controlled by the operator?

**Comment by rlopez133** [comment]
Hi Lars,

Wanted to start off by saying thanks for all the PRs! On to your questions.

I updated the document this morning to better reflect the `provisioning` interface after you gave the update of breaking up `baremetal` and `provisioning` bridges. [Step 11](https://openshift-kni.github.io/baremetal-deploy/4.4/Deployment.html#preparing-the-provisioner-node-for-openshift-install_ipi-install-prerequisites) gives those details. It is expected that the operator assign an IP address for the provisioning interface

If the operator assigns the address it does not have to a `.1` address. However, typically the bootstrap VM will assign `.2` and this can be modified via the `bootstrapProvisioningIP` parameter in the install-config.yaml (we are in the process of adding these details in the docs) and the `clusterProvisioningIP` can also be modified defaults to `.3` and also modified in the install-config.yaml

The bootstrap VM by default you don't need to do anything it automatically just gets assigned an address in IPv4 defaults to `172.22.0.2`

Aside from all the above, I was curious, have you tried using the [Ansible playbook](https://openshift-kni.github.io/baremetal-deploy/4.5/Ansible%20Playbook%20Install) for deployment?

**Comment by larsks** [comment]
@rlopez133 I'm trying to walk through the documentation first, because I'd like to understand what's happening before I try that "automate all the things" approach. I do plan to try the playbook once I've achieved success with the docs.

**Comment by iranzo** [comment]
@larsks when you've the chance, can you review the changes introduced by Roger to see if there's something missing to cover in this request?

Thanks!

**Comment by rlopez133** [comment]
> One that is unclear from the docs: is it _necessary_ to set `provisioningNetworkCIDR` in install-config.yaml`, or will this default to `172.22.0.0/24`if not provided explicitly? In either case, it's probably worth mentioning that the value here must correspond to the address assigned to the`provisioning`interface earlier using`nmcli`.

In the configuring we give an example of the install-config.yaml Everything in there is required to have some sort of value. Anything optional is left in the 7.2 
https://openshift-kni.github.io/baremetal-deploy/4.4/Deployment.html#configuring-the-install-config-file_ipi-install-prerequisites

Starting with OCP4.4, it is required and in the install-config.yaml we give examples such as
```
    provisioningNetworkInterface: <NIC1>
    provisioningNetworkCIDR: <CIDR> # i.e. fd00:1101::1/64
```

where we are giving them examples of what is required. I think the CIDR though we can give an example of 172.22.0.0/24 as well

**Comment by rlopez133** [comment]
We added the new install-config table in section 7.2 so I think this is now covered. Feel free to reopen if needed.
