### ISSUE TITLE
Dead link for creating new disconnected registry

### ISSUE THREAD

**Issue by pavanbheeman** [openshift-kni/baremetal-deploy#428]
In the link https://openshift-kni.github.io/baremetal-deploy/4.5/Ansible%20Playbook%20Disconnected%20Install Under 3. Using an Existing Registry, the link for creating new disconnected registry is dead

**Comment by iranzo** [comment]
Thanks Pavan, Use this one in the meantime: https://openshift-kni.github.io/baremetal-deploy/4.5/Deployment#ipi-install-creating-a-disconnected-registry_ipi-install-prerequisites
