### ISSUE TITLE
Section 8.5 ("Mirroring the repository") is unclear

### ISSUE THREAD

**Issue by larsks** [openshift-kni/baremetal-deploy#442]
In section 8.5, the documentation says:

> Mirror the remote install images to the local repository.
> 
> ```
> [user@registry ~]$ /usr/local/bin/oc adm release mirror \
>   -a pull-secret-update.json
>   --from=$UPSTREAM_REPO \
>   --to-release-image=$LOCAL_REG/$LOCAL_REPO:${VERSION} \
>   --to=$LOCAL_REG/$LOCAL_REPO
> ```

Why are we using placeholder variables here, rather than providing literal values? There is a following example that attempts to provide example values, but it looks like this:

> ```
> UPSTREAM_STREAM=${RELEASE_IMAGE}
> LOCAL_REG=<registry_FQDN>:<registry_port>
> LOCAL_REPO='ocp4/openshift4'
> ```

It defines `UPSTREAM_STREAM` rather than `UPSTREAM_REPO`, and it doesn't actually show what the value should look like. This entire section could be more clear.

**Comment by rlopez133** [comment]
The UPSTREAM_REPO AND UPSTREAM_STREAM piece -- easy fix got it.

Regarding the value of RELEASE_IMAGE. The issue with giving a concrete UPSTREAM_REPO example is the fear someone will just copy that value and run the command which would be inherently wrong. 

What we thought would work would be to include the RELEASE_IMAGE which was captured as a variable when retrieving the OpenShift Installer (chapter 5.1.1 or 5.2.1)

**Comment by larsks** [comment]
> What we thought would work would be to include the RELEASE_IMAGE which was captured as a variable when retrieving the OpenShift Installer (chapter 5.1.1 or 5.2.1)

Maybe just some verbage referring back to that section would help. Especially since this entire section is labelled "option", there's a good chance that someone walking through the command here won't be in the same shell session they were back in section 5.

**Comment by larsks** [comment]
I submitted a simple PR (although I'm not sure I got the asciidoc syntax correct for cross-page links).
