### ISSUE TITLE
Is documentation on setting up local registry missing certificate information?

### ISSUE THREAD

**Issue by larsks** [openshift-kni/baremetal-deploy#454]
I've set up a local registry as per [section 8](https://openshift-kni.github.io/baremetal-deploy/4.4/Deployment.html#ipi-install-creating-a-disconnected-registry_ipi-install-prerequisites). Everything looks fine, except the bootstrap vm doesn't seem to be able to access the registry. In the logs for the registry service, I see:

```
2020/06/08 21:50:15 http: TLS handshake error from 128.31.28.94:45220: remote error: tls: bad certificate
```

...which makes sense, because nowhere do we configure the bootstrap vm with a certificate for contacting the local registry service. Is there something missing from the documentation, have a missed a step, or is this expected output?

**Comment by DirectedSoul1** [comment]
Hi @larsks , thanks for raising the issue, so you have created the disconnected registry, I would like to know if the created registry is reachable from the `provisioning` host from where you are running playbooks. Can you please let us know if 

1.  The registry is accessible using the below commands?
```
curl -k -6 -u user:password https://registry.example.com:5000/v2/_catalog
{"repositories":["<Your-Repository>"]}
```
Also, the `rc` for the below
```
curl -I -s http://registry.example.com/$RHCOS_OPENSTACK_URI | grep HTTP
curl -I -s http://registry.example.com/$RHCOS_QEMU_URI | grep HTTP
```

**Comment by rlopez133** [comment]
@larsks aside from the above, I guess the next obvious question is if you did all the steps from 8.1 thru 8.6?

**Comment by larsks** [comment]
On the provisioning host, the registry is accessible, and the `oc adm release mirror...` command completes just fine. 

On the bootstrap vm, the registry is *reachable*:

```
[root@31-28-91 ~]# curl -k -u $username:$password https://provisioner.cnv.massopen.cloud:5000/v2/_catalog
{"repositories":["ocp4/openshift4"]}
```

`/etc/containers/registries.conf` looks like this:

```
[[registry]]
location = "quay.io/openshift-release-dev/ocp-release"
insecure = false
mirror-by-digest-only = true

[[registry.mirror]]
location = "provisioner.cnv.massopen.cloud:5000/ocp4/openshift4"
insecure = false


[[registry]]
location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
insecure = false
mirror-by-digest-only = true

[[registry.mirror]]
location = "provisioner.cnv.massopen.cloud:5000/ocp4/openshift4"
insecure = false
```

I don't think the install is actually using the registry, 

> `curl -I -s http://registry.example.com/$RHCOS_OPENSTACK_URI | grep HTTP`

The image cache is working fine and I think is orthagonal to this question.

**Comment by DirectedSoul1** [comment]
Yeah the above `curl` command only applies if you have created the caching webserver; now i can think of is whether the `pullsecret` variable has been set with the correct certificate to access the disconnected registry ; it should look something like 

```
pullsecret='{"auths":{"cloud.openshift.com":{"auth":<SomeHash>, ,"registry.redhat.io"=:{"auth":<someHash>, "registry.svc.ci.openshift.org": {"auth":<someHash>, "registry.example.com:5000":{"auth": "base64-encoded-value=","email": "noemail@localhost"}}}'
```
I would verify is this `{"auth": "base64-encoded-value=","email": "noemail@localhost"}}}'` value is properly set. I can think of this as a possible missing/mis-configured value as this error message is `bad-certificate` as seen from above logs.

**Comment by rlopez133** [comment]
@larsks can you share a copy of your install-config.yaml file and scrub out your passwords?

**Comment by rlopez133** [comment]
@larsks any update here?

**Comment by rlopez133** [comment]
Closing as it has not been updated in some time. If you need to reopen feel free.
