### ISSUE TITLE
Add support for proxy with certificates

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/baremetal-deploy#462]
The current playbook does support installing with proxy https://openshift-kni.github.io/baremetal-deploy/latest/Ansible%20Playbook%20Install#ansible-playbook-appendix-using-a-proxy-with-your-ansible-playbook, but if the proxy requires an additional certificate, you may need to configure an additional trust bundle (see https://github.com/openshift/installer/blob/master/docs/user/customization.md#proxy)

**Comment by rlopez133** [comment]
@e-minguez question if say you use a disconnected registry which requires a AdditionalTrustBundle, do you know how to handle when you have 2?

**Comment by e-minguez** [comment]
no idea :D The docs also say https://docs.openshift.com/container-platform/4.4/authentication/certificate-types-descriptions.html#proxy-certificates_ocp-certificates

**Comment by rlopez133** [comment]
@e-minguez ok :) Other Q, is there a customer running into this currently?

**Comment by e-minguez** [comment]
> @e-minguez ok :) Other Q, is there a customer running into this currently?

AFAIK no, I only wanted to validate this in my lab. Thanks.

**Comment by rlopez133** [comment]
@e-minguez I've asked in slack channel to see what are the options.

**Comment by iranzo** [comment]
to be covered in #518 ?
