### ISSUE TITLE
CNV deploy.sh never times out

### ISSUE THREAD

**Issue by chadcrum** [openshift-kni/baremetal-deploy#471]
The following referenced line in the deploy.sh script can lead to a forever loop if the CNV operator never completes:
https://github.com/openshift-kni/baremetal-deploy/blob/147495c947109f52a7817b62e0def10f435ec17e/features/cnv/deploy.sh#L34

Would be nice to have another variable that limits the amount of intervals while goes through or an overall timeout.

/cc @tiraboschi

**Comment by rlopez133** [comment]
@markmc can we close this?

**Comment by rlopez133** [comment]
Feel free to reopen if necessary.
