### ISSUE TITLE
Root device hints not available in 4.5 or earlier

### ISSUE THREAD

**Issue by abays** [openshift-kni/baremetal-deploy#476]
We include root device hint support in our Ansible installer for 4.5+, but they're not actually available until 4.6.  We should remove them for 4.5 and earlier.

**Comment by iranzo** [comment]
Hi  @abays I was checking about the commited code and comparing against commit cbacea42f4f9d38ef83a6aaff34c056cfc83d079 and seems that the conditionals are >= 4.6 or < 4.6 so this should be covered.

Can you give me some hints about what should be fixed?

Thanks!

**Comment by abays** [comment]
@iranzo My bad!  I fixed the issue with PR #477 and forgot to resolve this.  Closing this one out now.
