### ISSUE TITLE
[RFE] Allow to force IPMI or REDFISH to bypass autodetection

### ISSUE THREAD

**Issue by iranzo** [openshift-kni/baremetal-deploy#497]
Some servers that have latest Dell iDRAC version are presenting issues with redfish:

~~~diff
[kni@worker-2 internal-integration]$ diff ~/clusterconfigs.old/install-config.yaml.bkup ~/clusterconfigs/install-config.yaml.bkup  | grep address
<           address: ipmi://10.19.28.16:623
>           address: redfish://10.19.28.16/redfish/v1/Systems/System.Embedded.1
<           address: ipmi://10.19.28.17:623
>           address: redfish://10.19.28.17/redfish/v1/Systems/System.Embedded.1
[kni@worker-2 internal-integration]$
~~~

If we can define it to be configurable instead of automatic detection we might be able to workaround this situation.

Currently the servers fail to get managed via redfish (R640)

**Comment by ptrnull** [comment]
> Currently the servers fail to get managed via redfish (R640)
The playbooks end with no erros but the OCP installation fails because it can't bring the workers up and some COs are degraded (authentication, console, ingress, monitoring, operator-lifecycle-manager-packageserver).

**Comment by rlopez133** [comment]
Issue has been fixed.
