### ISSUE TITLE
Add proxy instructions into IPI on BM documentation

### ISSUE THREAD

**Issue by rlopez133** [openshift-kni/baremetal-deploy#518]
Currently we don't capture any steps on how to use a proxy within our docs.

**Comment by iranzo** [comment]
Isn't this covered in https://openshift-kni.github.io/baremetal-deploy/4.6/Deployment.html#ipi-install-setting-proxy-settings-within-install-config_ipi-install-configuration-files ?

**Comment by rlopez133** [comment]
It is. This issue can be closed.
