### ISSUE TITLE
59_cleanup_bootstrap.yml does not catch paused bootstrap vm's

### ISSUE THREAD

**Issue by p3ck** [openshift-kni/baremetal-deploy#524]
The clean up playbook doesn't catch paused vm's.

We've experienced running out of disk space on our provision host and once this happens the cleanup routine never cleans this up.

**Comment by iranzo** [comment]
Hi, @p3ck  reviewing the playbook, it should already contain the fix as it was merged in #525 can we close this now? have you verified it again?

Thanks!
Pablo

**Comment by p3ck** [comment]
It's a corner case that doesn't trigger very often, but I manually tested it by simulating the situation.  I feel confident we can close this now.
