### ISSUE TITLE
Missing selinux flag in the rhcos cache container

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/baremetal-deploy#526]
This misses the `:Z` flag

https://github.com/openshift-kni/baremetal-deploy/blob/05d490ae602c3066b219d419c46ceee226951865/ansible-ipi-install/roles/installer/tasks/24_rhcos_image_cache.yml#L163

In my case, I've screwed my config because I did a `restorecon` in my home folder and now the rhcos_image_cache container cannot server the images :sweat_smile:

**Comment by rlopez133** [comment]
Yeah I have this note as to the reasoning of why. 

#Leaving SELinux details alone and not using ":z"
#for the provision_cache_store due to issues attempting
#to revert context. Leaving behavior as it was previously
#to avoid breaking other user environments.
