### ISSUE TITLE
Generated PDF issue on code sections

### ISSUE THREAD

**Issue by jparrill** [openshift-kni/baremetal-deploy#538]
Hey there, I've seen an issue when a PDF is generated from a website version of the deployment guide, seems to be the same on other generated PDF . You could see the issue in the screenshot:

![image](https://user-images.githubusercontent.com/1569950/96558516-12977700-12bc-11eb-90ae-c2fe9011547b.png)

**Comment by iranzo** [comment]
Thanks Juanma, on the HTML version it works fine, I'll review the asciidoctor generation of the PDF version

**Comment by iranzo** [comment]
Checking via https://github.com/asciidoctor/asciidoctor-pdf/issues/1802 on upstream project

**Comment by iranzo** [comment]
@jparrill while the PR is reviewed please check https://deploy-preview-539--baremetal-deploy.netlify.app/ for the rendered PR in order to validate it fulfills your needs.

Thanks

**Comment by jparrill** [comment]
LGTM :+1:
