### ISSUE TITLE
Improve suggestions when a python module is missing in the system

### ISSUE THREAD

**Issue by ptrnull** [openshift-kni/baremetal-deploy#553]
When the python module netaddr is not installed and you run the installation playbooks, the error says:

fatal: [rna1-worker-0.rna1.cloud.lab.eng.bos.redhat.com]: FAILED! => {"changed": false, "msg": "Missing python module(s) ['netaddr'] on localhost\n"}

An improvement would be to tell the user the RPM package to be installed instead of the python module:
Something like:

fatal: [rna1-worker-0.rna1.cloud.lab.eng.bos.redhat.com]: FAILED! => {"changed": false, "msg": "Missing python module(s) ['netaddr'] on localhost, **install the rpm python3-netaddr\**n"}

**Comment by rlopez133** [comment]
Hey @ptrnull 

I thought of this initially but this gets complicated between knowing what OS the user is deploying from and if they have python2 or python3 installed. Thus, there wasn't an easy way to determine which package was required, so I just chose to mention the python module name.

**Comment by ptrnull** [comment]
Hello @rlopez133 , great minds think alike.

You are right, covering the most majority number of OS and their packages is a lot of work. Not worth the effort, let the user look for it depending on their packet manager, giving the python module name is already a good clue.
Thanks!
