### ISSUE TITLE
55_customize_filesystem playbook uses hardcoded role_path

### ISSUE THREAD

**Issue by p3ck** [openshift-kni/baremetal-deploy#570]
55_customize_filesystem playbook allows for custom filesystem changes to the coreos nodes via ignition config.

But the implementation is hard coded to look in {{ role_path }} which makes it hard to re-use a role properly.

We have one jumphost running these playbooks for multiple clusters at the same time.

Suggestion would be to allow for an override variable to allow the fake root filesystem to be hosted elsewhere.

**Comment by iranzo** [comment]
With https://github.com/openshift-kni/baremetal-deploy/pull/571 merged, this should be closed or anything missng here @p3ck ?

Thanks

**Comment by p3ck** [comment]
Yes - this can be closed.  Thanks!
