### ISSUE TITLE
[Question] The IPI documentation mentions needing 10GB network switches

### ISSUE THREAD

**Issue by kanadaj** [openshift-kni/baremetal-deploy#596]
The IPI documentation mentions needing 10GB network switches. Is this actually a requirement? If so, why? It's never mentioned anywhere else, including the manual bare metal installation guide.

**Comment by iranzo** [comment]
Hi @kanadaj it comes from: https://docs.openshift.com/container-platform/4.6/installing/installing_bare_metal_ipi/ipi-install-prerequisites.html#node-requirements_ipi-install-prerequisites


I guess that you could use lower speed links, but that will affect deployment times on the infrastructure

**Comment by kanadaj** [comment]
@iranzo Yeah I get that that's what the official docs say, my point is that there isn't any justification of where this number comes from or why it's needed, and why it's not mentioned on the manual bare metal setup anywhere.

**Comment by kanadaj** [comment]
Actually, since I'm here I'll also ask - is it possible to set up Openshift so the router binds to a different network/IP (assuming it doesn't listen to 0.0.0.0) so internal comms use a dedicated private network while public services are all on a public connection?

**Comment by iranzo** [comment]
I think that you're looking for something like https://github.com/openshift/cluster-network-operator to customize the networks of yor cluster
