### ISSUE TITLE
[RFE] Make 'redfish_inspection' parameter smarter

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/baremetal-deploy#677]
It would be nice when running the playbook with ipmi only nodes, the `redfish_inspection` parameter to be automatically configured as 'false' to avoid unneeded inspections and timeouts.

**Comment by iranzo** [comment]
Edu, how do suggest to determine that nodes are IPMI only?

**Comment by e-minguez** [comment]
> Edu, how do suggest to determine that nodes are IPMI only?

```
yq e '.platform.baremetal.hosts[].bmc.address' install-config.yaml
ipmi://10.19.136.22
ipmi://10.19.136.23
ipmi://10.19.136.24
ipmi://10.19.143.29
```

**Comment by iranzo** [comment]
The install config is generated *before* calling the installer based on the data gathered by the script, by default, the inventory the playbook uses takes "IPMI" as the url for BMC controller no matter if it's ipmi or redfish as this is later deducted by probing for the features provided (this is part of the 10_validation.yml playbook)

If you check, it has several install-config.j2, once for regular systems and another one for virtual media which is the one defining idrac-virtualmedia or redfish-virtualmedia for the host's var 'ipmi_address' defined in the inventory, based on versions and support for VM for that particular host (HP and Dell so far)
