### ISSUE TITLE
Wrong steps to remove bootstrap in 4.6

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/baremetal-deploy#682]
```
for i in $(sudo virsh list | tail -n +3 | grep bootstrap | awk {'print $2'});
do
  sudo virsh destroy $i;
  sudo virsh undefine $i;
  sudo virsh vol-delete $i --pool default;
  sudo virsh vol-delete $i.ign --pool default;
done
```

[Now it seems](https://github.com/openshift/installer/commit/490fa13a6ca7dec386a01385b32ca36dfd410e5d) the bootstrap VM is created in its own libvirt storage pool. I guess the instructions from 4.7 should apply to 4.6 as well (at least 4.6.19 which is the one I'm using right now)

```
for i in $(sudo virsh list | tail -n +3 | grep bootstrap | awk {'print $2'});
do
  sudo virsh destroy $i;
  sudo virsh undefine $i;
  sudo virsh vol-delete $i --pool $i;
  sudo virsh vol-delete $i.ign --pool $i;
  sudo virsh pool-destroy $i;
  sudo virsh pool-undefine $i;
done
```

**Comment by iranzo** [comment]
Yes, this was an issue we discussed and apparently came in, thanks, I'll update the conditional
