### ISSUE TITLE
Manifests vs openshift folders customizations

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/baremetal-deploy#683]
`openshift-install create manifests` creates an `openshift` folder and a `manifests` one.

https://github.com/openshift-kni/baremetal-deploy/blob/ba3508f7c7a6d115271415c094676d8305ae3014/ansible-ipi-install/roles/installer/tasks/50_extramanifests.yml#L2-L14

This allows you to add extra objects within the `openshift` folder, but no within the `manifests` one.

It would be nice to include both.

**Comment by iranzo** [comment]
@colonwq as you worked on this, do you want to extend it?
Thx

**Comment by colonwq** [comment]
I have chatted with Edu. This patch looks good to me and solves an issue I would have reached soon.
