### ISSUE TITLE
RFE: boot mode settings?

### ISSUE THREAD

**Issue by iranzo** [openshift-kni/baremetal-deploy#688]
If we're going to use IPV6 or virtualmedia, it would be good to validate that system is configured with proper values before starting installation

**Comment by e-minguez** [comment]
I guess that in general a 'precheck' would be nice for things like DNS hostnames, reachability, free space for the bootstrap VM/registry/rhcos images/etc.,

**Comment by iranzo** [comment]
There are currently checks for the APIVIP and the DNSVIP, but even without DNS hostnames the installation and operation works fine (or at least, dhcp-obtained ones), but the other ones are definitely useful, thx!
