### ISSUE TITLE
containers.podman collection

### ISSUE THREAD

**Issue by smalleni** [openshift-kni/baremetal-deploy#758]
Whenever I am trying to create a disconnected registry I am facing issues with the containers.podman collection. It seems like we install the module from git directly into `ansible/-ipi-install/collections/ansible_collections`. Should we not install it/expect user to install it from galaxy for stability instead of using latest code from git?

```
ERROR! couldn't resolve module/action 'containers.podman.podman_container'. This often indicates a misspelling, missing collection, or incorrect module path.
```

**Comment by smalleni** [comment]
@iranzo FYI

**Comment by iranzo** [comment]
@smalleni if your system has internet connectivity you can use it from ansible-galaxy, the way it's included in the repo is as submodule, so as long as you git clone --recursive:

![image](https://user-images.githubusercontent.com/312463/118647754-f9b75b80-b7e1-11eb-8c29-cd8796163c4a.png)


You should get the version with the submodule that you could interactively update.

The prior container module was not  a submodule and was a bit outdated and causing issues with recent podman versions, hence why the current submodule approach was used.

**Comment by iranzo** [comment]
As reference, this came by https://github.com/openshift-kni/baremetal-deploy/issues/679 and was closed via https://github.com/openshift-kni/baremetal-deploy/pull/703

**Comment by smalleni** [comment]
> @smalleni if your system has internet connectivity you can use it from ansible-galaxy, the way it's included in the repo is as submodule, so as long as you git clone --recursive:
> 
> ![image](https://user-images.githubusercontent.com/312463/118647754-f9b75b80-b7e1-11eb-8c29-cd8796163c4a.png)
> 
> You should get the version with the submodule that you could interactively update.
> 
> The prior container module was not a submodule and was a bit outdated and causing issues with recent podman versions, hence why the current submodule approach was used.

Makes sense, thanks!
