### ISSUE TITLE
Unclear instructions for worker-rt

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/baremetal-deploy#76]
https://github.com/openshift-kni/baremetal-deploy/blob/master/features/performance/README.md says to label nodes intended to be worker-rt as:

```
oc label node <node_name> machineconfiguration.openshift.io/role=worker-rt
```

vs MCP README https://github.com/openshift-kni/baremetal-deploy/blob/master/features/mcp/README.md

```
oc label $node node-role.kubernetes.io/worker-rt=""
```

Are both needed?

**Comment by rlopez133** [comment]
@e-minguez whom should this be assigned too?

**Comment by slintes** [comment]
`oc label $node node-role.kubernetes.io/worker-rt=""` is correct.

And it is fixed already, see https://github.com/openshift-kni/baremetal-deploy/pull/85/files#diff-b4ea8dee615c682ed431a7cab5e26c6cR7

/close
