### ISSUE TITLE
Performance folder: readme examples and 'all or nothing'

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/baremetal-deploy#78]
https://github.com/openshift-kni/baremetal-deploy/tree/master/features/performance#environment-variables

It would be nice to add some examples. For instance, for `ISOLATED_CPUS` is "0-2" valid? or it needs to be "0,1,2"?

Also, it is 'all or nothing'? What if I want to deploy just the RT kernel?

**Comment by rlopez133** [comment]
@e-minguez whom should this be assigned too?

**Comment by e-minguez** [comment]
I think this is pointless now. See https://github.com/openshift-kni/cnf-features-deploy
