### ISSUE TITLE
add support for bmc type of irmc

### ISSUE THREAD

**Issue by p3ck** [openshift-kni/baremetal-deploy#811]
Currently the only options for BMC control is redfish and ipmi.  And redfish is limited to Dell and HP.

install-config.yml already supports irmc but the ansible ipi playbook and template does not support populating from the template correctly.

**Comment by hs0210** [comment]
> install-config.yml already supports irmc but the ansible ipi playbook and template does not support populating from the template correctly.

This problem still exists. For doing IPI test with DCI on iRMC, currently we have to manually modify the template. Could someone please take a look and fix this issue?

**Comment by p3ck** [comment]
Can you provide the modifications you made to the template?  Thanks

**Comment by hs0210** [comment]
I replaced all `ipmi` with `irmc` using `sed`.
```
sed -i -e 's/ipmi/irmc/g' install-config.j2
```
