### ISSUE TITLE
ansible ipi playbooks fail to find 4.10 rhcos.json file

### ISSUE THREAD

**Issue by p3ck** [openshift-kni/baremetal-deploy#830]
It seems the rhcos.json location has changed with 4.10 and it has broken the ansible-ipi-install playbooks..  

https://github.com/openshift-kni/baremetal-deploy/blob/4410400316e717c86282c63950ef4e9908f80f36/ansible-ipi-install/roles/installer/tasks/23_rhcos_image_paths.yml#L11

The above code is looking here for the rhcos.json file
```
https://raw.githubusercontent.com/openshift/installer/f2cbbed3749d281478fac59f20a6eea9c91b1e75/data/data/rhcos.json
```

But the actual location is here:
```
https://raw.githubusercontent.com/openshift/installer/f2cbbed3749d281478fac59f20a6eea9c91b1e75/data/data/coreos/rhcos.json
```

The old location still works for 4.9

**Comment by tonyskapunk** [comment]
It stopped being placed in the "old" location after this change: https://github.com/openshift/installer/pull/5252

The documentation of the "new" location was added in: https://github.com/openshift/installer/pull/5453
