### ISSUE TITLE
is ansible really needed?

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/baremetal-deploy#84]
Currently the [baremetal-prep.sh](https://github.com/openshift-kni/baremetal-deploy/blob/master/baremetal-prep/baremetal-prep.sh) script requires ansible to create the [install-config.yaml file](https://github.com/openshift-kni/baremetal-deploy/blob/master/baremetal-prep/baremetal-prep.sh#L156).
As it is just for a simple template/substitution, I think a bash script with envsubst/sed script/python script would be better so you won't need to subscribe to the ansible channel nor download a few unneeded packages

**Comment by davidvossel** [comment]
+1 to reducing dependencies to the bare minimum. I see no reason for ansible to be involved here.

**Comment by schmaustech** [comment]
I am cool with this idea but how are you handling the MAC addresses/ipmi IP/ipmi creds for all the baremetal hosts?

**Comment by e-minguez** [comment]
We currently use `envsubst` for that kind of stuff. See https://github.com/openshift-kni/baremetal-deploy/tree/master/features/sriov where we replace previously exported environment variables from a `myvars` file
