### ISSUE TITLE
install-steps.md / Configure the install-config and metal3-config

### ISSUE THREAD

**Issue by mazzystr** [openshift-kni/baremetal-deploy#88]
Step 5 is unnecessary.  Combine with Step 7 and reduce the number of steps overall.

**Comment by sreichar** [comment]
Which section's step 5, I counted about seven step 5s that also have a step 7.

**Comment by mazzystr** [comment]
@sreichar  Section `Configure the install-config and metal3-config` Step 5

**Comment by rlopez133** [comment]
@mazzystr Step 5 has all the environment substitutions. Step 7 the clusterconfigs/openshift dir doesn't exist yet as it is created in Step 6.
